### ISSUE TITLE
Leading underscore

### ISSUE THREAD

**Issue by hacknug** [tachyons-css/tachyons-visibility#4]
The visibility module has a leading underscore before every `_position: absolute !important;` declaration on [its source file](https://github.com/tachyons-css/tachyons-visibility/blob/master/src/tachyons-visibility.css) but not on [the compiled version](https://github.com/tachyons-css/tachyons-visibility/blob/master/css/tachyons-visibility.css) which only has it on the default property.

Is this a bug of some sort?

**Comment by mrkhdly** [comment]
Tachyons v5 will become a monorepo so this issue is being closed, if the issue is still relevant please open an issue with the main repo https://github.com/tachyons-css/tachyons/issues/new & link to this one
